mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as authViews

urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path("center/", include("center.urls", namespace="center")),
    path("vaccine/", include("vaccine.urls", namespace="vaccine")),
    path("campaign/", include("campaign.urls", namespace="campaign")),
    path("accounts/", include("user.urls", namespace="user")),
    path("password_reset/", authViews.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        authViews.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        authViews.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        authViews.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/user/urls.py
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("change-password/", views.change_password, name="change-password"),
    path("profile-view/", views.profile_view, name="profile-view"),
    path("profile-update/", views.profile_update, name="profile-update"),
    path("verify-email/", views.email_verificatin_request, name="verify-email"),
    path("email/activate/<uidb64>/<token>/", views.email_verifier, name="email-activate"),
]

mysite/vaccine/urls.py
from django.urls import path
from vaccine import views

app_name = "vaccine"

urlpatterns = [
    path("", views.VaccineList.as_view(), name="list"),
    path("<int:id>/", views.VaccineDetail.as_view(), name="detail"),
    path("create/", views.CreateVaccine.as_view(), name="create"),
    path("update/<int:id>/", views.UpdateVaccine.as_view(), name="update"),
    path("delete/<int:id>/", views.DeleteVaccine.as_view(), name="delete"),
]

mysite/vaccine/models.py
from django.db import models

# Create your models here.
class Vaccine(models.Model):
    name = models.CharField("Vaccine Name", max_length=32)
    description = models.TextField(max_length=1024)
    number_of_doses = models.IntegerField(default=1)
    interval = models.IntegerField(default=0, help_text="Please provide interval in days")
    storage_temperature = models.IntegerField(null=True, blank=True, help_text="Provide the temperature in Celcius")
    minimum_age = models.IntegerField(default=0)

    def __str__(self):
        return self.name

mysite/vaccine/forms.py
from django.forms import ModelForm
from vaccine.models import Vaccine

class VaccineForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(VaccineForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            
    class Meta:
        model = Vaccine
        fields = "__all__"

mysite/vaccine/views.py
from django.shortcuts import render
from django.views import View
from vaccine.models import Vaccine
from django.http import Http404, HttpResponseRedirect
from vaccine.forms import VaccineForm
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator

@method_decorator(login_required, name="dispatch")
class VaccineList(View):
    def get(self, request):
        vaccine_list = Vaccine.objects.all().order_by("name")
        paginator = Paginator(vaccine_list, 2)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context = {
            "page_obj": page_obj
        }
        return render(request, "vaccine/vaccine-list.html", context)

@method_decorator(login_required, name="dispatch")
class VaccineDetail(View):
    def get(self, request, id):
        try:
            vaccine = Vaccine.objects.get(id=id)
        except Vaccine.DoesNotExist:
            raise Http404("Vaccine instance not found")
        
        context = {
            "object": vaccine,
        }
        return render(request, "vaccine/vaccine-detail.html", context)

@method_decorator(login_required, name="dispatch")
@method_decorator(permission_required("vaccine.add_vaccine", raise_exception=True), name="dispatch")
class CreateVaccine(View):
    form_class = VaccineForm
    template_name = "vaccine/create-vaccine.html"

    def get(self, request):
        context = {
            "form": self.form_class
        }
        return render(request, self.template_name, context)
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Vaccine Created Successfully")
            return HttpResponseRedirect(reverse("vaccine:list"))
        messages.error(request, "Please enter valid data")
        return render(request, self.template_name, {"form": form})

@method_decorator(login_required, name="dispatch")
@method_decorator(permission_required("vaccine.change_vaccine", raise_exception=True), name="dispatch")
class UpdateVaccine(View):
    form_class = VaccineForm
    template_name = "vaccine/update-vaccine.html"

    def get(self, request, id):
        vaccine = get_object_or_404(Vaccine, id=id)
        context = {
            "form": self.form_class(instance=vaccine),
        }
        return render(request, self.template_name, context)
    
    def post(self, request, id):
        vaccine = get_object_or_404(Vaccine, id=id)
        form = self.form_class(request.POST, instance=vaccine)
        if form.is_valid():
            form.save()
            messages.success(request, "Vaccine Updated Successfully")
            return HttpResponseRedirect(reverse("vaccine:detail", kwargs={"id": vaccine.id}))
        messages.error(request, "Please enter valid data")
        return render(request, self.template_name, {"form": form})

@method_decorator(login_required, name="dispatch")
@method_decorator(permission_required("vaccine.delete_vaccine", raise_exception=True), name="dispatch")
class DeleteVaccine(View):
    template_name = "vaccine/delete-vaccine.html"

    def get(self, request, id):
        vaccine = get_object_or_404(Vaccine, id=id)
        context = {
            "object": vaccine
        }
        return render(request, self.template_name, context)
    
    def post(self, request, id):
        Vaccine.objects.filter(id=id).delete()
        messages.success(request, "Vaccine Deleted Successfully")
        return HttpResponseRedirect(reverse("vaccine:list"))

mysite/vaccine/templates/vaccine/create-vaccine.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Create Vaccine</title>
{% endblock title %}

{% block content %}
<div class="card p-3">
  <div class="card-body">
    <h4 class="mb-3">Fill the following details to create a new vaccine</h4>
    {% include "components/form.html" with form_name="Create Vaccine" %}
  </div>
</div>
{% endblock content %}

mysite/vaccine/templates/vaccine/delete-vaccine.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Delete Vaccine</title>
{% endblock title %}

{% block content %}
<div class="card p-3">
    <div class="card-text">
        <h4>Are you sure you want to delete {{ object.name }} ?</h4>
        {% include "components/form.html" with form_name="Delete Vaccine" %}
    </div>
</div>
{% endblock content %}

mysite/vaccine/templates/vaccine/update-vaccine.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Update Vaccine</title>
{% endblock title %}

{% block content %}
<div class="card p-3">
  <div class="card-body">
    <h4 class="mb-3">Fill the following details to update the vaccine details.</h4>
    {% include "components/form.html" with form_name="Update Vaccine" %}
  </div>
</div>
{% endblock content %}

mysite/vaccine/templates/vaccine/vaccine-detail.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Vaccine Details</title>
{% endblock title %}

{% block content %}
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title mb-4"><i class="fas fa-map-marker-alt"></i> Vaccine Details</h5>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Vaccine Name
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.name }}
      </div>
    </div>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Description
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.description }}
      </div>
    </div>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Storage Temperature
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.storage_temperature }}
      </div>
    </div>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Number of doses
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.number_of_doses }}
      </div>
    </div>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Interval
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.interval }}
      </div>
    </div>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Minimum Age
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.minimum_age }}
      </div>
    </div>

    <div class="row mb-1 btn-container">
      <div class="col-12">
        <button class="btn btn-sm btn-success m-1">
          <a href="{% url 'vaccine:update' object.id %}">
            <i class="fas fa-pen"></i> Update Vaccine
          </a>
        </button>

        <button class="btn btn-sm btn-danger m-1">
          <a href="{% url 'vaccine:delete' object.id %}">
            <i class="fas fa-trash"></i> Delete Vaccine
          </a>
        </button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

mysite/vaccine/templates/vaccine/vaccine-list.html
{% extends 'mysite/base.html' %}
{% block title %} 
    <title>Vaccine List</title>
{% endblock title %}

{% block content %}
<div class="mt-3">

  <div class="d-flex align-items-center justify-content-between">
    <h3 class="text-center">
      <i class="fas fa-syringe"></i> Vaccine List
    </h3>
    <a href="{% url 'vaccine:create' %}"><i class="fas fa-plus"></i> Create Vaccine</a>
  </div>

  <table class="table table-responsive table-hover">
    <thead>
      <tr>
        <th scope="col">Vaccine Name</th>
        <th scope="col">Number of Doses</th>
        <th scope="col">Interval</th>
        <th scope="col">Minimum Age</th>
        <th scope="col">Select</th>
      </tr>
    </thead>

    <tbody>
      {% for vaccine in page_obj %}
      <tr>
        <td>{{vaccine.name|upper}}</td>
        <td>{{ vaccine.number_of_doses }}</td>
        <td>{{ vaccine.interval }}</td>
        <td>{{ vaccine.minimum_age }}</td>
        <td><a href="{% url 'vaccine:detail' vaccine.id %}" class="btn-sm btn-outline-primary">View Details</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include "components/pagination.html" %}
</div>
{% endblock content %}