mysite/campaign/urls.py
from django.urls import path 
from campaign import views

app_name = "campaign"

urlpatterns = [
    path("", views.CampaignListView.as_view(), name="campaign-list"),
    path("<int:pk>/", views.CampaignDetailView.as_view(), name="campaign-detail"),
    path("create/", views.CampaignCreateView.as_view(), name="campaign-create"),
    path("update/<int:pk>/", views.CampaignUpdateView.as_view(), name="campaign-update"),
    path("delete/<int:pk>/", views.CampaignDeleteView.as_view(), name="campaign-delete"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as authViews

urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path("center/", include("center.urls", namespace="center")),
    path("vaccine/", include("vaccine.urls", namespace="vaccine")),
    path("campaign/", include("campaign.urls", namespace="campaign")),
    path("accounts/", include("user.urls", namespace="user")),
    path("password_reset/", authViews.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        authViews.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        authViews.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        authViews.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/user/urls.py
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("change-password/", views.change_password, name="change-password"),
    path("profile-view/", views.profile_view, name="profile-view"),
    path("profile-update/", views.profile_update, name="profile-update"),
    path("verify-email/", views.email_verificatin_request, name="verify-email"),
    path("email/activate/<uidb64>/<token>/", views.email_verifier, name="email-activate"),
]

mysite/campaign/models.py
from django.db import models
from center.models import Center
from vaccine.models import Vaccine
from django.contrib.auth import get_user_model

User = get_user_model()

class Campaign(models.Model):
    center = models.ForeignKey(Center, on_delete=models.CASCADE)
    vaccine = models.ForeignKey(Vaccine, on_delete=models.CASCADE)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    agents = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return str(self.vaccine.name).upper() + " | " + str(self.center.name).upper()


class Slot(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    date = models.DateField(null=True, blank=True)
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    max_capacity = models.IntegerField(default=0, null=True, blank=True)
    reserved = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return str(self.date) + " | " + str(self.start_time) + " to " + str(self.end_time)

mysite/campaign/forms.py
from django.forms import ModelForm
from campaign.models import Campaign

class CampaignForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(CampaignForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Campaign
        fields = "__all__"

mysite/campaign/views.py
from typing import Any
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from campaign.models import Campaign
from vaccination.models import Vaccination
from campaign.forms import CampaignForm
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy


class CampaignListView(LoginRequiredMixin, generic.ListView):
    model = Campaign
    template_name = "campaign/campaign-list.html"
    paginate_by = 10
    ordering = ["-id"]


class CampaignDetailView(LoginRequiredMixin, generic.DetailView):
    model = Campaign
    template_name = "campaign/campaign-detail.html"

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context["registration"] = Vaccination.objects.filter(campaign=self.kwargs["pk"]).count()
        return context


class CampaignCreateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Campaign
    form_class = CampaignForm
    permission_required = ("campaign.add_campaign",)
    template_name = "campaign/campaign-create.html"
    success_message = "Campaign Created Successfully"
    success_url = reverse_lazy("campaign:campaign-list")

class CampaignUpdateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Campaign
    form_class = CampaignForm
    permission_required = ("campaign:change_campaign",)
    template_name = "campaign/campaign-update.html"
    success_message = "Campaign Updated Successfully"
    success_url = reverse_lazy("campaign:campaign-list")

class CampaignDeleteView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    model = Campaign
    template_name = "campaign/campaign-delete.html"
    permission_required = ("campaign.delete_campaign",)
    success_message = "Campaign Deleted Successfully"
    success_url = reverse_lazy("campaign:campaign-list")
    

mysite/campaign/templates/campaign/campaign-create.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Create New Campaign</title>
{% endblock title %}

{% block content %}
<div class="card p-3">
    <div class="card-body">
        <h4 class="mb-3">Fill the following details to create a new campaign</h4>
        {% include "components/form.html" with form_name="Create Campaign" %}
    </div>
</div>
{% endblock content %}

mysite/campaign/templates/campaign/campaign-delete.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Delete Campaign</title>
{% endblock title %}

{% block content %}
<div class="card p-3">
    <div class="card-body">
        <h4>Are you sure you want to delete "{{ object }}" ?</h4>
        {% include "components/form.html" with form_name="Delete Campaign" %}
    </div>
</div>
{% endblock content %}

mysite/campaign/templates/campaign/campaign-detail.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Campaign Details</title>
{% endblock title %}

{% block content %}
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title mb-4"><i class="fas fa-calendar"></i> Campaign Details</h5>
    <div class="container">

      <div class="row mb-1">
        <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
          Center Name
        </div>
        <div class="col-7 col-sm-8 col-md-9 col-lg-10">
          {{ object.center.name }}
        </div>
      </div>

      <div class="row mb-1">
        <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
          Vaccine Name
        </div>
        <div class="col-7 col-sm-8 col-md-9 col-lg-10">
          {{ object.vaccine.name }}
        </div>
      </div>

      <div class="row mb-1">
        <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
         Start Date
        </div>
        <div class="col-7 col-sm-8 col-md-9 col-lg-10">
          {{ object.start_date }}
        </div>
      </div>

      <div class="row mb-1">
        <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
         End Date
        </div>
        <div class="col-7 col-sm-8 col-md-9 col-lg-10">
          {{ object.end_date }}
        </div>
      </div>

      <div class="row mb-1">
        <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
         Registrations
        </div>
        <div class="col-7 col-sm-8 col-md-9 col-lg-10">
          {{ registration }}
        </div>
      </div>

      <div class="row mb-1">
        <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
         Agents Assigned
        </div>
        <div class="col-7 col-sm-8 col-md-9 col-lg-10">
          {% for agent in object.agents.all %}
          {{agent.get_full_name }},
          {% endfor %}
        </div>
      </div>

      <div class="row mb-1 btn-container">
        <div class="col-12">
          <button class="btn btn-sm btn-dark m-1">
            <a href="#"><i class="fas fa-eye"></i> View Registrations</a>
          </button>

          <button class="btn btn-sm btn-primary m-1">
            <a href="#"><i class="fas fa-eye"></i> View Slots</a>
          </button>

          <button class="btn btn-sm btn-success m-1">
            <a href="{% url 'campaign:campaign-update' object.id %}"><i class="fas fa-pen"></i> Update Campaign</a>
          </button>

          <button class="btn btn-sm btn-danger m-1">
            <a href="{% url 'campaign:campaign-delete' object.id %}"><i class="fas fa-trash"></i> Delete Campaign</a>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

mysite/campaign/templates/campaign/campaign-list.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Campaign List</title>
{% endblock title %}

{% block content %}
<div class="mt-3">
    
  <div class="d-flex align-items-center justify-content-between">
        <h3 class="text-center"><i class="fas fa-calendar"></i> Campaign List</h3>
        <a href="{% url 'campaign:campaign-create' %}"><i class="fas fa-plus"></i> Create Campaign</a>
  </div>
    
  <table class="table table-responsive table-hover text-center">
    <thead>
      <tr>
          <th scope="col">Vaccine</th>
          <th scope="col">Center</th>
          <th scope="col">Start Date</th>
          <th scope="col">End Date</th>
          <th scope="col">Select</th>
      </tr>
    </thead>
    <tbody>
        {% for campaign in object_list %}
        <tr>
          <td>{{ campaign.vaccine }}</td>
          <td>{{ campaign.center.name }}</td>
          <td>{{ campaign.start_date }}</td>
          <td>{{ campaign.end_date }}</td>
          <td><a href="{% url 'campaign:campaign-detail' campaign.id %}" class="btn-sm btn-outline-primary">View Details</a></td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
  
  {% include "components/pagination.html"%}
</div>
{% endblock content %}

mysite/campaign/templates/campaign/campaign-update.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Update Campaign</title>
{% endblock title %}

{% block content %}
<div class="card p-3">
   <div class="card-body">
    <h4 class="mb-3">Fill the following details to update campaign details</h4>
    {% include "components/form.html" with form_name="Update Campaign" %}
   </div>
</div>
{% endblock content %}