mysite/center/urls.py
from django.urls import path
from center import views

app_name = "center"

urlpatterns = [
    path("", views.center_list, name="list"),
    path("<int:id>/", views.center_detail, name="detail"),
    path("create/", views.create_center, name="create"),
    path("update/<int:id>/", views.update_center, name="update"),
    path("delete/<int:id>/", views.delete_center, name="delete"),
    path("<int:center_id>/storage/", views.StorageList.as_view(), name="storage-list"),
    path("storage/<int:pk>/", views.StorageDetail.as_view(), name="storage-detail"),
    path("<int:center_id>/storage/create/", views.CreateStorage.as_view(), name="storage-create"),
    path("storage/update/<int:pk>/", views.StorageUpdate.as_view(), name="storage-update"),
    path("storage/delete/<int:pk>/", views.StorageDelete.as_view(), name="storage-delete"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as authViews

urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path("center/", include("center.urls", namespace="center")),
    path("vaccine/", include("vaccine.urls", namespace="vaccine")),
    path("campaign/", include("campaign.urls", namespace="campaign")),
    path("accounts/", include("user.urls", namespace="user")),
    path("password_reset/", authViews.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        authViews.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        authViews.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        authViews.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/user/urls.py
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("change-password/", views.change_password, name="change-password"),
    path("profile-view/", views.profile_view, name="profile-view"),
    path("profile-update/", views.profile_update, name="profile-update"),
    path("verify-email/", views.email_verificatin_request, name="verify-email"),
    path("email/activate/<uidb64>/<token>/", views.email_verifier, name="email-activate"),
]

mysite/center/models.py
from django.db import models
from vaccine.models import Vaccine

# Create your models here.
class Center(models.Model):
    name = models.CharField(max_length=124)
    address = models.TextField(max_length=500)

    def __str__(self):
        return self.name


class Storage(models.Model):
    center = models.ForeignKey(Center, on_delete=models.CASCADE)
    vaccine = models.ForeignKey(Vaccine, on_delete=models.CASCADE)
    total_quantity = models.IntegerField(default=0)
    booked_quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.center.name + " | " + self.vaccine.name

mysite/center/forms.py
from django.forms import ModelForm
from center.models import Center, Storage

class CenterForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(CenterForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
    class Meta:
        model = Center
        fields = "__all__"

class StorageForm(ModelForm):
    def __init__(self, center_id, *args, **kwargs):
        super(StorageForm, self).__init__(*args, **kwargs)
        self.fields["center"].queryset = Center.objects.filter(id=center_id)
        self.fields["center"].disabled = True
        self.fields["booked_quantity"].disabled = True
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
    class Meta:
        model = Storage
        fields = "__all__"

mysite/center/views.py
from typing import Any
from django.shortcuts import render
from center.models import Center, Storage
from center.forms import CenterForm, StorageForm
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

@login_required
def center_list(request):
    objects = Center.objects.all().order_by("name")
    paginator = Paginator(objects, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, "center/center-list.html", context)

@login_required
def center_detail(request, id):
    object = Center.objects.get(id=id)
    context = {
        "center": object,
    }
    return render(request, "center/center-detail.html", context)

@login_required
@permission_required("center.add_center", raise_exception=True)
def create_center(request):
    if request.method == "POST":
        form = CenterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Vaccination Center Created Successfully")
            return HttpResponseRedirect(reverse("center:list"))
        messages.error(request, "Please enter valid data")
        return render(request, "center/create-center.html", {"form": form})
    # GET
    context = {
        "form": CenterForm()
    }
    return render(request, "center/create-center.html", context)

@login_required
@permission_required("center.change_center", raise_exception=True)
def update_center(request, id):
    try:
        center = Center.objects.get(id=id)
    except Center.DoesNotExist:
        raise Http404("Center instance is not found")
    
    if request.method == "POST":
        form = CenterForm(request.POST, instance = center)
        if form.is_valid():
            form.save()
            messages.success(request, "Vaccination Center updated successfully")
            return HttpResponseRedirect(reverse("center:detail", kwargs={"id": center.id}))
        messages.error(request, "Please enter valid data")
        return render(request, "center/update-center.html", {"form": form})
    # Get
    context = {
        "form": CenterForm(instance = center)
    }
    return render(request, "center/update-center.html", context)

@login_required
@permission_required("center.delete_center", raise_exception=True)
def delete_center(request, id):
    try:
        center = Center.objects.get(id=id)
    except Center.DoesNotExist:
        raise Http404("Center instance not found")
    
    if request.method == "POST":
        center.delete()
        messages.success(request, "Vaccination Center Deleted Successfully")
        return HttpResponseRedirect(reverse("center:list"))
    # GET
    context = {
        "center": center,
    }
    return render(request, "center/delete-center.html", context)


class StorageList(LoginRequiredMixin, generic.ListView):
    queryset = Storage.objects.all()
    template_name = "storage/storage-list.html"
    ordering = ["id"]
    paginate_by = 2

    def get_queryset(self):
        return super().get_queryset().filter(center_id = self.kwargs["center_id"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["center_id"] = self.kwargs["center_id"]
        return context

class StorageDetail(LoginRequiredMixin, generic.DetailView):
    model = Storage
    template_name = "storage/storage-detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["available_quantity"] = self.object.total_quantity - self.object.booked_quantity
        return context

class CreateStorage(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Storage
    form_class = StorageForm
    template_name = "storage/storage-create.html"
    success_message = "Storage Created Successfully"
    permission_required = ("center.add_storage",)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["center_id"] = self.kwargs["center_id"]
        return kwargs
    
    def get_initial(self):
        initial = super().get_initial()
        initial["center"] = Center.objects.get(id=self.kwargs["center_id"])
        return initial
    
    def get_success_url(self):
        return reverse("center:storage-list", kwargs={"center_id": self.kwargs["center_id"]})


class StorageUpdate(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Storage
    form_class = StorageForm
    template_name = "storage/storage-update.html"
    success_message = "Storage Updated Successfully"
    permission_required = ("center.change_storage",)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["center_id"] = self.get_object().center.id
        return kwargs
    
    def get_success_url(self) -> str:
        return reverse("center:storage-list", kwargs={"center_id": self.get_object().center.id})

class StorageDelete(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    model = Storage
    template_name = "storage/storage-delete.html"
    success_message = "Storage Deleted Successfully"
    permission_required = ("center.delete_storage",)

    def get_success_url(self) -> str:
        return reverse("center:storage-list", kwargs={"center_id": self.get_object().center.id})

mysite/center/templates/center/center-detail.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Center Detail</title>
{% endblock title %}

{% block content %}
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title mb-4"><i class="fas fa-map-marker-alt"></i> Center Details</h5>
    
    <div class="row mb-1">
        <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
         Center Name
        </div>
        <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{center.name}}
        </div>
    </div>
    
    <div class="row mb-1">
        <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Address
        </div>
        <div class="col-7 col-sm-8 col-md-9 col-lg-10">
          <pre>{{center.address}}</pre>
        </div>
    </div>
    
    <div class="row mb-1 btn-container">
      <div class="col-12">

        <button class="btn btn-sm btn-dark m-1">
          <a href="{% url 'center:storage-list' center.id %}">
            <i class="fas fa-eye"></i> View Storage
          </a>
        </button>

        <button class="btn btn-sm btn-success m-1">
          <a href="{% url 'center:update' center.id %}">
            <i class="fas fa-pen"></i> Update Center
          </a>
        </button>
            
        <button class="btn btn-sm btn-danger m-1">
          <a href="{% url 'center:delete' center.id %}">
            <i class="fas fa-trash"></i> Delete Center
          </a>
        </button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

mysite/center/templates/center/center-list.html
{% extends 'mysite/base.html' %} 

{% block title %} 
    <title>Center List</title>
{% endblock title %} 

{% block content %}
<div class="mt-3">

  <div class="d-flex align-items-center justify-content-between">
    <h3 class="text-center">
      <i class="fas fa-map-marker-alt"></i> Center List
    </h3>
    <a href="{% url 'center:create' %}"><i class="fas fa-plus"></i> Create Center</a>
  </div>

  <table class="table table-responsive table-hover">
    <thead>
      <tr>
        <th scope="col">Center Name</th>
        <th scope="col">Select</th>
      </tr>
    </thead>
    
    <tbody>
      {% for object in page_obj %}
      <tr>
        <td>{{object.name|upper}}</td>
        <td><a href="{% url 'center:detail' object.id %}" class="btn-sm btn-outline-primary">View Details</a></td>
      </tr>
      {% endfor %}
    </tbody>
    
  </table>

  {% include "components/pagination.html" %}
</div>
{% endblock content %}

mysite/center/templates/center/create-center.html
{% extends 'mysite/base.html' %} 

{% block title %} 
    <title>Create Center</title>
{% endblock title %} 

{% block content %}
<div class="card p-3">
  <div class="card-body">
    <h4 class="mb-3">Fill the following details to create a new center</h4>
    {% include "components/form.html" with form_name="Create Center" %}
  </div>
</div>
{% endblock content %}

mysite/center/templates/center/delete-center.html
{% extends 'mysite/base.html' %} 

{% block title %} 
<title>Delete Center</title>
{% endblock title %}

{% block content %}
<div class="card p-3">
    <div class="card-body">
        <h4>Are you sure you want to delete "{{ center.name }}" ?</h4>
        {% include "components/form.html" with form_name="Delete Center"  %}
    </div>
</div>
{% endblock content %}

mysite/center/templates/center/update-center.html
{% extends 'mysite/base.html' %} 

{% block title %} 
    <title>Update Center</title>
{% endblock title %} 

{% block content %}
<div class="card p-3">
  <div class="card-body">
    <h4 class="mb-3">Fill the following details to update this center</h4>
    {% include "components/form.html" with form_name="Update Center" %}
  </div>
</div>
{% endblock content %}