mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as authViews

urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path("center/", include("center.urls", namespace="center")),
    path("vaccine/", include("vaccine.urls", namespace="vaccine")),
    path("campaign/", include("campaign.urls", namespace="campaign")),
    path("accounts/", include("user.urls", namespace="user")),
    path("password_reset/", authViews.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        authViews.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        authViews.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        authViews.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/user/urls.py
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("change-password/", views.change_password, name="change-password"),
    path("profile-view/", views.profile_view, name="profile-view"),
    path("profile-update/", views.profile_update, name="profile-update"),
    path("verify-email/", views.email_verificatin_request, name="verify-email"),
    path("email/activate/<uidb64>/<token>/", views.email_verifier, name="email-activate"),
]

mysite/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.base_user import BaseUserManager
from django.utils import timezone


BLOOD_GROUP_CHOICES = [
    ("A+", "A+"),
    ("A-", "A-"),
    ("B+", "B+"),
    ("B-", "B-"),
    ("O+", "O+"),
    ("O-", "O-"),
    ("AB+", "AB+"),
    ("AB-", "AB-"),
]

DOCUMENT_CHOICES = [
    ("Voter Id", "Voter Id"),
    ("Passport", "Passport"),
    ("Citizenship Number", "Citizenship Number"),
]

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("Email is required")
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser = True")

        return self._create_user(email, password, **extra_fields)



class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=254, blank=True, null=True)
    middle_name = models.CharField(max_length=254, blank=True, null=True)
    last_name = models.CharField(max_length=254, blank=True, null=True)
    date_of_birth = models.DateField(null=True, blank=True, help_text="Enter the date in this format: Year-Month-Day")
    gender = models.CharField(max_length=1, choices=[("M", "Male"), ("F", "Female")])
    blood_group = models.CharField(max_length=3, null=True, blank=True, choices=BLOOD_GROUP_CHOICES)
    identity_document_type = models.CharField(max_length=32, choices=DOCUMENT_CHOICES, null=True, blank=True)
    identity_document_number = models.CharField(max_length=255, null=True, blank=True)
    photo = models.ImageField(null=True, upload_to="profileImage/")
    date_joined = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(auto_now=True)
    is_email_verified = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    def get_full_name(self):
        return f"{self.first_name} {self.middle_name} {self.last_name}"
    
    objects = UserManager()

    

mysite/user/forms.py
from typing import Any
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django.forms import ModelForm

User = get_user_model()

class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
    
    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "middle_name",
            "last_name",
            "date_of_birth",
            "gender",
            "photo",
            "identity_document_type",
            "identity_document_number",
        ]


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
    
    class Meta:
        model = User
        fields = "__all__"

class ChangePasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
    
    class Meta:
        model = User
        fields = "__all__"

class ProfileUpdateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
    
    class Meta:
        model = User
        fields = [
            "first_name",
            "middle_name",
            "last_name",
            "gender",
            "photo",
            "date_of_birth",
            "identity_document_type",
            "identity_document_number",
        ]

mysite/user/views.py
from django.shortcuts import render
from django.contrib import messages
from user.forms import SignupForm, LoginForm, ChangePasswordForm, ProfileUpdateForm
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden, HttpResponseBadRequest
from django.urls import reverse
from django.contrib.auth import authenticate, login as user_login, logout as user_logout, update_session_auth_hash
from user.email import send_email_verification
from django.contrib.auth import get_user_model
from user.utils import EmailVerificationTokenGenerator
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str
from django.contrib.auth.decorators import login_required

User = get_user_model()

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Account Created Successfully! Please Login")
            return HttpResponseRedirect(reverse("index"))
        messages.error(request, "Please enter valid data")
        return render(request, "user/signup.html", {"form": form})
    # Get Request
    context = {
        "form": SignupForm()
    }
    return render(request, "user/signup.html", context)

def login(request):
    if request.method == "POST":
        form = LoginForm(request, request.POST)
        if form.is_valid():
            email = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(email=email, password=password)
            if user is not None:
                user_login(request, user)
                messages.success(request, "Logged in successfully")
                return HttpResponseRedirect(reverse("index"))
            messages.error(request, "Please enter valid credentials")
            return HttpResponseRedirect(reverse("user:login"))
        messages.error(request, "Please enter valid credentials")
        return HttpResponseRedirect(reverse("user:login"))
    # GET 
    context = {
        "form": LoginForm()
    }
    return render(request, "user/login.html", context)


@login_required
def logout(request):
    user_logout(request)
    messages.info(request, "Logged out successfully")
    return HttpResponseRedirect(reverse("user:login"))

@login_required
def change_password(request):
    if request.method == "POST":
        form = ChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, "Password Changed Successfully")
            return HttpResponseRedirect(reverse("index"))
        messages.error(request, "Please enter valid data")
        return render(request, "user/change-password.html", {"form": form})
    # GET
    context = {
        "form": ChangePasswordForm(request.user)
    }
    return render(request, "user/change-password.html", context)

@login_required
def profile_view(request):
    context = {
        "user": request.user
    }
    return render(request, "user/profile-view.html", context)

@login_required
def profile_update(request):
    if request.method == "POST":
        form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "Profile Updated Successfully")
            return HttpResponseRedirect(reverse("user:profile-view"))
        messages.error(request, "Please enter valid data")
        return render(request, "user/profile-update.html", {"form": form})
    # GET request
    context = {
        "form": ProfileUpdateForm(instance=request.user)
    }
    return render(request, "user/profile-update.html", context)

@login_required
def email_verificatin_request(request):
    if not request.user.is_email_verified:
        send_email_verification(request, request.user.id)
        return HttpResponse("Email Verification Link sent to your email address")
    return HttpResponseForbidden("Email already verified")

@login_required
def email_verifier(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(id=uid)
    except:
        user = None
    

    if user == request.user:
        if EmailVerificationTokenGenerator.check_token(user, token):
            user.is_email_verified = True
            user.save()
            messages.success(request, "Email address verified")
            return HttpResponseRedirect(reverse("user:profile-view"))
        return HttpResponseBadRequest("Invalid request")
    return HttpResponseForbidden("You dont have permission to use this link")

mysite/user/templates/user/change-password.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Change Password</title>
{% endblock title %}

{% block content %}
<div class="card p-3">
  <div class="card-body">
    <h4>Fill the following details to change your password</h4>
    {% include "components/form.html" with form_name="Change Password" %}
  </div>
</div>
{% endblock content %}

mysite/user/templates/user/email-verify.html
{% autoescape off %}  
Hi {{ full_name }},  
Please click on the link to verfy your email,  
http://{{ domain }}{% url 'user:email-activate' uidb64=uid token=token %}  
{% endautoescape %}  

mysite/user/templates/user/login.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Login</title>
{% endblock %}

{% block content %}
<div class="card p-3">
   <div class="card-body">
      <h4>Enter your email and password to login</h4>
      {% include "components/form.html" with form_name="Login" %}
   </div>
   <p class="p-3">
      <a href="#">Reset Password</a>
   </p>
</div>
{% endblock content %}

mysite/user/templates/user/profile-update.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Profile Update</title>
{% endblock title %}

{% block content %}
<div class="m-2 p-2">
  <h4>Fill the following details to update the profile</h4>
  {% include "components/auth-form.html" with form_name="Update Profile" %}
</div>
{% endblock content %}

mysite/user/templates/user/profile-view.html
{% extends "mysite/base.html" %}

{% block title %} 
    <title>Profile Details</title>
{% endblock title %}

{% block content %}
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title mb-4">
      <i class="fas fa-user"></i> Profile Details
    </h5>
    <div class="container">
      <div class="row">
        <div class="col-12 col-lg-4">
          {% if user.photo %}
          <img src={{ user.photo.url }} alt="Profile Picture" class="profile-img">
          {% endif %}
        </div>
        <div class="col-12 col-lg-8">
          <div class="row mb-1">
            <p>Here is your profile details. Please keep your details updated.</p>
          </div>
          <div class="row mb-1">
            <div class="col-5 col-sm-4 fw-bold">
              Email Address
            </div>
            <div class="col-7 col-sm-8">
              {{ user.email }}
              {% if user.is_email_verified %}
              <i>(Email Verified)</i>
              {% else %}
              (<a href="{% url 'user:verify-email' %}">Verify Email</a>)
              {% endif %}
            </div>
          </div>

          <div class="row mb-1">
            <div class="col-5 col-sm-4 fw-bold">
              First Name
            </div>
            <div class="col-7 col-sm-8">
              {{ user.first_name }}
            </div>
          </div>

          <div class="row mb-1">
            <div class="col-5 col-sm-4 fw-bold">
              Middle Name
            </div>
            <div class="col-7 col-sm-8">
              {{ user.middle_name }}
            </div>
          </div>

          <div class="row mb-1">
            <div class="col-5 col-sm-4 fw-bold">
              Last Name
            </div>
            <div class="col-7 col-sm-8">
              {{ user.last_name }}
            </div>
          </div>

          <div class="row mb-1">
            <div class="col-5 col-sm-4 fw-bold">
              Date of Birth
            </div>
            <div class="col-7 col-sm-8">
              {{ user.date_of_birth }}
            </div>
          </div>

          <div class="row mb-1">
            <div class="col-5 col-sm-4 fw-bold">
              Gender
            </div>
            <div class="col-7 col-sm-8">
              {{ user.gender }}
            </div>
          </div>

          <div class="row mb-1">
            <div class="col-5 col-sm-4 fw-bold">
              Identity Document Type
            </div>
            <div class="col-7 col-sm-8">
              {{ user.identity_document_type }}
            </div>
          </div>

          <div class="row mb-1">
            <div class="col-5 col-sm-4 fw-bold">
              Identity Document Number
            </div>
            <div class="col-7 col-sm-8">
              {{ user.identity_document_number }}
            </div>
          </div>

          <div class="row mb-1">
            <div class="col-5 col-sm-4 fw-bold">
              Date Joined
            </div>
            <div class="col-7 col-sm-8">
              {{ user.date_joined }}
            </div>
          </div>
          <div class="row mb-1 btn-container">
            <div class="col-12">
              <button class="btn btn-sm btn-success m-1">
                <a href="{% url 'user:profile-update' %}"><i class="fas fa-pen"></i>
                  Update Profile</a>
              </button>

              <button class="btn btn-sm btn-danger m-1">
                <a href="{% url 'user:change-password' %}"><i class="fas fa-pen"></i>
                  Change Password</a>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

mysite/user/templates/user/signup.html
{% extends 'mysite/base.html' %} 

{% block title %} 
    <title>Signup</title>
{% endblock title %}

{% block content %}
<div class="card p-3">
 <div class="card-body">
    <h4>Fill the following details to create a new account</h4>
    {% include "components/auth-form.html" with form_name="Signup" %}
 </div>
</div>
{% endblock content %}